-- CreateEnum
CREATE TYPE "BugStatus" AS ENUM ('OPEN', 'UNASSIGNED', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REOPENED');

-- AlterTable
ALTER TABLE "BugReport" ADD COLUMN     "assignee" TEXT,
ADD COLUMN     "resolvedAt" TIMESTAMP(3),
ADD COLUMN     "status" "BugStatus" NOT NULL DEFAULT 'OPEN',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
