sonar.projectKey=bug-report-portal
sonar.projectName=Bug Report Portal
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,uploads/**,data/**,prisma/migrations/**

sonar.sourceEncoding=UTF-8
